# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_ordinalized}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mandaryn"]
  s.date = %q{2010-08-18}
  s.description = %q{This is a simple acts_as gem providing the active record models with ordinal numbers. The ordinals numbering is per query, but should work nicely with will paginate showing correct ordinal numbers on paginated results.}
  s.email = %q{mandaryyyn@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "acts_as_ordinalized.gemspec",
     "lib/acts_as_ordinalized.rb",
     "test/test_ordinalized.rb"
  ]
  s.homepage = %q{http://github.com/mandaryn/acts_as_ordinalized}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{simple gem providing active record collections with ordinal numbers}
  s.test_files = [
    "test/test_ordinalized.rb"
  ]

  s.add_dependency('will_paginate')
  s.add_dependency('rails', '~> 2.3.5')
end

